project_id = "thyowehliqgrjkeknoza"

[functions.notify-new-registration]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.automation-api]
verify_jwt = false

[functions.translate-category]
verify_jwt = false